<?php
$html = <<<EOD
({corrInfo:{
   "SC1873":{correctness:"85%",delay:"13"},"MU2452":{correctness:"80%",delay:"19"},"MU3655":{correctness:"91%",delay:"6"},"CZ6399":{correctness:"91%",delay:"6"},"CA8215":{correctness:"70%",delay:"27"},"MU4406":{correctness:"94%",delay:"10"},"NH5788":{correctness:"47%",delay:"53"},"MU2456":{correctness:"52%",delay:"43"},"MU2454":{correctness:"63%",delay:"31"},"SC1341":{correctness:"48%",delay:"52"},"ZH4939":{correctness:"72%",delay:"32"},"HU7187":{correctness:"88%",delay:"13"},"CA8209":{correctness:"72%",delay:"32"},"ZH4935":{correctness:"66%",delay:"37"},"SC1475":{correctness:"86%",delay:"13"},"CZ9168":{correctness:"80%",delay:"19"},"ZH1475":{correctness:"86%",delay:"13"},"ZH1873":{correctness:"85%",delay:"13"},"CA1341":{correctness:"47%",delay:"53"},"CZ6606":{correctness:"94%",delay:"10"},"NH5790":{correctness:"70%",delay:"27"},"MU2460":{correctness:"87%",delay:"18"},"CA1873":{correctness:"85%",delay:"13"},"CZ9174":{correctness:"87%",delay:"19"},"CZ9172":{correctness:"52%",delay:"43"},"CZ9170":{correctness:"63%",delay:"31"},"MU3019":{correctness:"88%",delay:"10"},"CA8205":{correctness:"66%",delay:"37"},"CA1475":{correctness:"86%",delay:"13"},"MF4778":{correctness:"94%",delay:"10"},"CZ3118":{correctness:"88%",delay:"10"},"MF1020":{correctness:"88%",delay:"10"},"MU3035":{correctness:"69%",delay:"36"},"ZH1341":{correctness:"47%",delay:"53"},"MF1040":{correctness:"69%",delay:"36"},"CZ3140":{correctness:"69%",delay:"38"},"MF4101":{correctness:"91%",delay:"6"},"ZH4941":{correctness:"70%",delay:"27"}   
   },
 extInfo : {
   
   "MF4778":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ6606",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "226",dis : "7" }, 
   zj : {url : '',info : "" },
   qibe:0}
   ,
   "MU2452":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:true,
   lqf:0,
   fdt:"2小时20分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "HU7187":{
   ml:"false",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时20分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "4" }, 
   zj : {url : 'http://www.hnair.com/hnairweb/FrameMain/wfmMainReady.aspx?strHref=1',info : "本航班支持网上值机，每日12:00后可办理次日北京始发国内航班的乘机手续，航班起飞前2小时停止办理。" },
   qibe:0}
   ,
   "SC1873":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA1873",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4" }, 
   zj : {url : 'http://www.shandongair.com.cn/web/shair_zh/',info : "本航班支持网上值机，每日13:00后可办理次日所有北京始发国内航班的乘机手续，航班起飞前2小时停止办理。" },
   qibe:0}
   ,
   "MU2454":{
   ml:"false",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时5分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "MU3655":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ6399",
   et:"true",
   ps:true,
   hot:false,
   lqf:0,
   fdt:"2小时10分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "ZH4939":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA8209",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时10分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : '',info : "" },
   qibe:0}
   ,
   "NH5788":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA1341",
   et:"true",
   ps:true,
   hot:false,
   lqf:0,
   fdt:"2小时5分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "",dis : "" }, 
   zj : {url : '',info : "" },
   qibe:0}
   ,
   "MU2456":{
   ml:"false",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "MU3019":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ3118",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:fa…",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : 'http://airport.csair.com/cki/app',info : "本航班支持网上值机，航班预计起飞前1天14:00开始至航班预计起飞时间前60分钟。请于航空公司网站办理网上值机。" },
   qibe:0}
   ,
   "CZ9172":{
   ml:"false",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"MU2456",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : 'http://airport.csair.com/cki/app',info : "本航班支持网上值机，航班预计起飞前1天14:00开始至航班预计起飞时间前60分钟。请于航空公司网站办理网上值机。" },
   qibe:0}
   ,
   "CZ6399":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:true,
   lqf:0,
   fdt:"2小时10分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : 'http://airport.csair.com/cki/app',info : "本航班支持网上值机，航班预计起飞前1天14:00开始至航班预计起飞时间前60分钟。请于航空公司网站办理网上值机。" },
   qibe:0}
   ,
   "MF4101":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ6399",
   et:"true",
   ps:true,
   hot:false,
   lqf:0,
   fdt:"2小时10分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "226",dis : "7" }, 
   zj : {url : '',info : "" },
   qibe:0}
   ,
   "SC1341":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA1341",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时5分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4" }, 
   zj : {url : 'http://www.shandongair.com.cn/web/shair_zh/',info : "本航班支持网上值机，每日13:00后可办理次日所有北京始发国内航班的乘机手续，航班起飞前2小时停止办理。" },
   qibe:0}
   ,
   "CA8215":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4" }, 
   zj : {url : 'http://airchina.travelsky.com/cab2c/getOckiConfig.do',info : "本航班支持网上值机，航班起飞前36小时即可办理北京始发国航实际运营国内航班的乘机手续，航班起飞前2小时停止办理。请您不晚于航班起飞前20分钟到达指定登机口登机。国际航班国内段暂不办理。" },
   qibe:0}
   ,
   "CA8209":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时10分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4" }, 
   zj : {url : 'http://airchina.travelsky.com/cab2c/getOckiConfig.do',info : "本航班支持网上值机，航班起飞前36小时即可办理北京始发国航实际运营国内航班的乘机手续，航班起飞前2小时停止办理。请您不晚于航班起飞前20分钟到达指定登机口登机。国际航班国内段暂不办理。" },
   qibe:0}
   ,
   "MU4406":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ6606",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "ZH1873":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA1873",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : '',info : "" },
   qibe:0}
   ,
   "SC1475":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CA1475",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时5分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4" }, 
   zj : {url : 'http://www.shandongair.com.cn/web/shair_zh/',info : "本航班支持网上值机，每日13:00后可办理次日所有北京始发国内航班的乘机手续，航班起飞前2小时停止办理。" },
   qibe:0}
   ,
   "CZ9168":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"MU2452",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时20分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : 'http://airport.csair.com/cki/app',info : "本航班支持网上值机，航班预计起飞前1天14:00开始至航班预计起飞时间前60分钟。请于航空公司网站办理网上值机。" },
   qibe:0}
   ,
   "CZ6606":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"",
   et:"true",
   ps:false,
   hot:true,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1133",dis : "4.5" }, 
   zj : {url : 'http://airport.csair.com/cki/app',info : "本航班支持网上值机，航班预计起飞前1天14:00开始至航班预计起飞时间前60分钟。请于航空公司网站办理网上值机。" },
   qibe:0}
   ,
   "MU3035":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ3140",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "1416",dis : "3" }, 
   zj : {url : 'http://mu.travelsky.com/mub2c/Cuss/cusshelp.html',info : "本航班支持网上值机，航班起飞前一天16:00到航班起飞前2小时，请于北京首都国际机场2号航站楼/值机H岛13号柜台办理。" },
   qibe:0}
   ,
   "MF1020":{
   ml:"true",
   sp:"0",
   spCity:"",
   spAirPort:"",
   cs:"CZ3118",
   et:"true",
   ps:false,
   hot:false,
   lqf:0,
   fdt:"2小时15分钟",
   fot:"0",
   acf:"50",   
   lcc:false,
   sc : {full : "226",dis : "7" }, 
   zj : {url : '',info : "" },
   qibe:0}
   }})
EOD;
print $html;

?>
